
services:
  backend:
    build: ./todo_backend
    ports:
      - 8080:8080
    networks:
      - todo_network
    depends_on:
      - mysqldb
    volumes:
      - backend_data:/data/todo_backend_mysql
    
  frontend:
    build: ./todo_frontend
    ports:
      - 3000:3000
    networks:
      - todo_network
    depends_on:
      - backend

  mysqldb:
    image: mysql
    networks:
      - todo_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tododb
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  todo_network:
    driver: bridge

volumes:
  backend_data:
  mysql_data: