spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysqldb:3306/mysql_todo
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    server:
        address: 0.0.0.0

    