spring:
    datasource:
        driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
        url: ${DB_URL:jdbc:mysql://mysqldb:3306/mysql_todo}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    # server:
    #     address: 0.0.0.0

    