---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv
  labels:
    name: dbpod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/lib/mysql
...