---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpvc
  labels:
    app: dbpod
spec:
  volumeName: dbpv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
...