---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv
  labels:
    name: dbpod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/lib/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpvc
  labels:
    app: dbpod
spec:
  volumeName: dbpv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbdeployment
  labels:
    app: dbpod
spec:
  selector:
    matchLabels:
      app: dbpod
  replicas: 1
  serviceName: dbdeployment # should be same as service name in metadata -> name
  template:
    metadata:     
      labels:
        app: dbpod
    spec:
      volumes:
        - name: dbvolume
          persistentVolumeClaim:
            claimName: dbpvc
      containers:
        - name: dbpod
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: dbvolume 
              mountPath: /var/lib/mysql
          env:
            # - name: DB_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: dbsecret
            #       key: DB_USERNAME_VALUE
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: dbsecret
            #       key: DB_PASSWORD_VALUE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: mysql_root_pass
            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom :
                configMapKeyRef :
                  name : dbconfigmap
                  key :  dbschema
---
apiVersion: v1
kind: Service
metadata: 
  name: dbservice
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  ClusterIP: None
  selector:
      app: dbpod
...